# fly.toml app configuration file generated for ff-studio-bot on 2024-10-14T17:02:32+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ff-studio-bot'
primary_region = 'lhr'

[build]

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
